### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by Ceci007**
## Milestone 2: User interface 
we added the user interface to the `main.rb` (input and output) and some game logic but the game logic is yet unfinished.
- displaying the instructions.
- Add some checks for the win cases, lose and draw.
- Input for the player's name
- displaying the board.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 
Hi @Ceci007 and @jelduran! You have done a nice job trying to implement most of the required classes for this project, however, there are some points I'd like you to focus on for this milestone:
- [ ] It is important that you focus on the game flow ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). This is supposed to help you think exhaustively about the game flow without getting distracted by the implementation details.
- [ ] The `main.rb` uses `puts/print` and `get.chomp` commands. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). All your declared classes will come in handy on the next milestone and you will definitely not put them in the `main.rb` file since that is what the `lib` folder is for.
- [ ] I have noticed that you have one commit for your entire pull request. It is a good practice to make your commits atomic so that they define small but important changes because this would help you explore your project more conveniently at a later stage. Point number 3 from [this article](https://medium.com/@judithmalnick/github-10-tips-for-good-pull-requests-6ad62319ed6) could shed some more light about `commit atomicity`.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Ceci007** [comment]
sorry for the Rubocop error, the 2 global variables are just for testing purposes after this we are going to remove them.

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- [ ] `[REQUIRED]` game asks the player to select from available moves
- [ ] `[REQUIRED]` game informs the player if the selected move is invalid

_You can use inline comments._

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by mosesogwo — APPROVED** [review]
**Hello! :wave: Good work :+1:  Your milestone is approved, but take note of the following:**

:point_right: Game loop shouldn't terminate with a fixed number of times as you have it (9). Instead use a loop that terminates only when there is a win or draw.

:point_right: Also, avoid disabling linter rules in your project.

_**Cheers:stars:**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
